language: c

sudo: false

cache:
  directories:
    - ~/.ghc
    - ~/.cabal

matrix:
  include:
    - env: CABALVER=2.0 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-2.0,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=2.0 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-2.0,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=2.0 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=2.0 GHCVER=8.2.2
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.2], sources: [hvr-ghc]}}
    - env: CABALVER=2.0 GHCVER=8.4.1
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.4.1], sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests

script:
 - cabal configure --enable-tests --enable-coverage -v2 -f dev
 - cabal build
 - cabal test --show-details=always
 - cabal sdist
 - cabal haddock | grep "100%" | wc -l | grep "1"

notifications:
  email: false
